### ISSUE TITLE
Question about the baselines used in the paper

### ISSUE THREAD

**Issue by rigggby** [salesforce/ctrl-sum#12]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Hi, thanks for sharing your great work! I have some question regarding the baseline result  in the paper, specifically in Table 6, is the BART here finetuned on the arXiv dataset like your CTRLsum? Also, is the result in this table all zero-shot (you did not train on these two specific tasks)? Thanks.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by jxhe** [comment]
Hi,

Thank you for your interest! 
1. Yes, the BART baseline in Table 6 is finetuned on the arXiv dataset as well
2. Yes, the results in Table 6 are zero-shot

**Comment by rigggby** [comment]
Hi, thanks for your answer and have a nice day!
