### ISSUE TITLE
how to do test-time keyword extraction?

### ISSUE THREAD

**Issue by aliencaocao** [salesforce/ctrl-sum#14]
In the research paper, it was mentioned that ctrl-sum can extract keywords at test time. May I know how do I do it? The provided tutorials are just for summaries, not keywords.
![image](https://user-images.githubusercontent.com/20109683/151651184-f567cc89-a9b6-40d8-8d06-27ed1f1f2274.png)

**Comment by jxhe** [comment]
The tutorials include instructions to extract keywords from the tagger:
https://github.com/salesforce/ctrl-sum#obtain-automatic-keywords-from-a-trained-tagger

but you need to train the tagger first using our script. If you want our pretrained tagger for direct use, drop me an email at junxianh@cs.cmu.edu and I can share the pretrained tagger with you.

**Comment by aliencaocao** [comment]
Hi, I have emailed you, thank you!

**Comment by jxhe** [comment]
I have sent over email, hope it is helpful!

**Comment by aliencaocao** [comment]
Hi, I have converted the pretrained tagger model you provided into ONNX which makes it much faster to load and run inference, I also made a simple inference flask server app that generates keywords from a given source. Would you be interested to see it and perhaps add it to this repository?

**Comment by jxhe** [comment]
Wow thanks a bunch! I would like to see it and feel free to open pull request for that.

**Comment by aliencaocao** [comment]
Ok sure. I do not think I will make it as a PR because actually no code from this ctrl-sum repo is being reused. I will make a new repo and once it's ready, I will tag you here. You can then decide now how to integrate it into your this repo.

**Comment by jxhe** [comment]
Thanks! With the easiest way I could refer to your repo in the readme so that people can just check your repo directly.

**Comment by aliencaocao** [comment]
Hi, sorry for the wait. I have just published my code for the pretrained tagger model here: https://github.com/aliencaocao/CTRLSum-tagger

**Comment by jxhe** [comment]
@aliencaocao Thank you a bunch! Just added reference to your repo in our README.
