### ISSUE TITLE
fairseq-train: error: argument --restore-file: expected one argument

### ISSUE THREAD

**Issue by YoonaX** [salesforce/ctrl-sum#3]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Hello, I try to train by running "bash scripts/train_bart.sh -g 0,1,2,3 -d cnndm"
But there is an error: error: argument --restore-file: expected one argument
I think I should reload the original Bart Model. 
Where I can download the model and How Can I reload the Model?
Thanks~ 

#### What's your environment?
 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 
 - GPU models and configuration:
 - Any other relevant information:

**Comment by jxhe** [comment]
Hi, you can run `bash scripts/train_bart.sh -g 0,1,2,3 -d cnndm -b [the bart checkpoint .pt file]`, where the bart model checkpoint can be downloaded from the [fairseq page](https://github.com/pytorch/fairseq/blob/master/examples/bart/README.md) (we use `bart.large` model)

**Comment by YoonaX** [comment]
Thanks, Now there's a new problem：
FileNotFoundError: [Errno 2] No such file or directory: 'data-bin/cnndm/dict.oraclewordsource.txt'

How should I load the vocabulary of the BART model?

**Comment by YoonaX** [comment]
I think I found the reason. I have a little problem with data processing. Haha！！

You have a slight problem here

bash scripts/binarize_dataset.ssh cnndm   ->   bash scripts/binarize_dataset.sh cnndm

Happy Lantern Festival！！！

**Comment by jxhe** [comment]
Thank you, and happy Lantern Festival!
