### ISSUE TITLE
package for CTRLsum (easy to use)

### ISSUE THREAD

**Issue by hyunwoongko** [salesforce/ctrl-sum#5]
Thanks for cool research. The results of this research were quite appealing to me, so I made the package to make it easier to use. The package is called `summarizers`. I ported the model you provided to Hugging Face Transformers, and I made it for use with codes 2 to 3 lines.  If anyone wants to try this model more easily, it would be good to use.

https://github.com/hyunwoongko/summarizers

Thanks for great research again.

**Comment by jxhe** [comment]
Thank you very much! I added references to your repo as well as the huggingface interface into README.

**Comment by hyunwoongko** [comment]
I ported the following name on the Hugging Face.
- https://huggingface.co/hyunwoongko/ctrlsum-cnndm
- https://huggingface.co/hyunwoongko/ctrlsum-arxiv
- https://huggingface.co/hyunwoongko/ctrlsum-bigpatent

Thanks a lot!

**Comment by jxhe** [comment]
Thank you! I have a question for the unconditional summarization example: the unconditional summaries are generated with empty keywords/prompts in the package, right? I am asking just for clarification since it is different from the paper which uses automatic keywords, while I think it is still good and simple without an additional tagger.

**Comment by hyunwoongko** [comment]
Yeah. because It is just first draft version. I will add BERT tagger later (next version) Thanks.

**Comment by zpppy** [comment]
hello，how to covert fairseq's CTRLsum to huggingface's CTRLsum。Thanks :)

**Comment by jxhe** [comment]
Hi, the pretrained model checkpoints are already avaiable at huggingface, but we don't have a training script to train CTRLsum using Huggingface.

However, you can train CTRLsum with huggingface easily --  just run our preprocessing script to prepare the data, then run huggingface's summarization example script [here](https://github.com/huggingface/transformers/blob/master/examples/pytorch/summarization/README.md) following our training hyperparameters.
